#!/usr/bin/env bash
echo "================================"
echo "🔐 Add Google Antigravity Account"
echo "================================"
echo ""
echo "Step 1: Run OpenClaw configuration"
echo "  distrobox enter openclaw-dev"
echo "  openclaw configure --section model"
echo ""
echo "Step 2: In the wizard:"
echo "  - Choose 'Add/update provider credentials'"
echo "  - Select 'google-antigravity'"
echo "  - Authenticate with your new Google account"
echo "  - Browser will open for OAuth"
echo ""
echo "Step 3: After adding account(s), run:"
echo "  bash /tmp/migrate-antigravity-accounts.sh"
echo ""
echo "================================"
echo ""
read -p "Press Enter to start OpenClaw configuration..."
distrobox enter openclaw-dev -- openclaw configure --section model
echo ""
echo "Running migration..."
distrobox enter openclaw-dev -- bash /tmp/migrate-antigravity-accounts.sh
echo ""
echo "✅ Done! Check the account list above."
